### ISSUE TITLE
feat: support for nx monorepos

### ISSUE THREAD

**Issue by inpt333** [rdlabo-team/ionic-angular-collect-icons#2]
### Describe the Feature Request

I've tried to execute the tool in an Nx monorepo by specifying as `project-path` the path to the Ionic Angular app. The changes in the `main.ts` are applied, but the file `use-icons` is not generated.

### Describe the Use Case

Being able to execute all the steps described in the guidelines with an Ionic Angular app in an Nx monorepo.

**Comment by rdlabo** [comment]
I use this in my monorepos and it works well.

```
npx @rdlabo/ionic-angular-collect-icons --project-path projects/store
```

Give me a small reproduction of a project that doesn't work.

**Comment by inpt333** [comment]
> I use this in my monorepos and it works well.
> 
> ```
> npx @rdlabo/ionic-angular-collect-icons --project-path projects/store
> ```
> 
> Give me a small reproduction of a project that doesn't work.

Is the file `use-icons.ts` generated in your case? If so, do you have all your icons spread among many different Nx libraries, or just in the app itself? In my case, I have them all in libraries.

**Comment by rdlabo** [comment]
This is an example of proper working.

```bash
npx @rdlabo/ionic-angular-collect-icons --project-path my-app
```


Does your project/path include src?
There do not seem to be any reproducible examples, so I will close this Issue.
